spring:
  datasource:
    springdb:
      jdbc-url: jdbc:mysql://localhost:3306/springdb?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: jeonguk

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: false

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: WARN
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE